start:
	- docker compose up -d
stop:
	- docker compose down
restart:
	- docker compose restart
strapi-install:
	- docker compose run strapi yarn install
strapi-build:
	- docker compose run strapi yarn build
app-build:
	- docker compose build app